spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/OpenUtility?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Yanru123.
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
