spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/OpenUtility
    username: ${DB_USER}
    password: ${DB_PASS}
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl