spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.24.176.40:3300/OpenUtility?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ALi123eCs

#  jpa:
#    hibernate:
#      ddl-auto: create-drop



#logging:
#  level:
#    web: debug
#    hikari:
#      auto-commit: true  # 启用自动提交
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
